# Generated by Django 3.1 on 2021-07-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_link',
            field=models.URLField(default='https://imgur.com/dQpzDHi'),
        ),
    ]
