# Generated by Django 3.1 on 2021-06-09 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='static/media/products/default_prod.jpg', upload_to='products'),
        ),
    ]
