# Generated by Django 3.1 on 2021-07-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_link',
            field=models.URLField(default='https://i.imgur.com/dQpzDHi.jpg'),
        ),
    ]
