# Generated by Django 3.1 on 2021-06-09 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210609_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default_prod.jpg', upload_to='products'),
        ),
    ]
