# Generated by Django 3.1 on 2021-06-11 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_variation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variation',
            options={'verbose_name': 'Variacion', 'verbose_name_plural': 'Variaciones'},
        ),
    ]
