# Generated by Django 3.1 on 2021-06-12 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cartitem_variations'),
        ('store', '0006_auto_20210611_1203'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
