# Generated by Django 3.1 on 2021-06-07 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_remove_category_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
    ]
