# Generated by Django 3.1 on 2021-06-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
